### ISSUE TITLE
.to() 0 inclusive

### ISSUE THREAD

**Issue by superhackerboy** [superhackerboy/totally-random#10]
I think that the `.to()` method should be inclusive to 0. The `color()` uses `.to()` to generate numbers but can't generate a 0 value. Since 0 is a valid number to RGB, RGBA, HSL, and HSLA, I think this needs to be changed. Thoughts?

**Comment by shadowtime2000** [comment]
As far as I can see, it looks like the `.between()` method is being used for `color()`.

**Comment by superhackerboy** [comment]
Oh, duh! I see that now. I added 3 more color options and accidentally switched from `between` to `to`. Gonna push it up now
