### ISSUE TITLE
Two names for the same function

### ISSUE THREAD

**Issue by superhackerboy** [superhackerboy/totally-random#11]
One of our methods `.color()` should be invoked even if a user runs `.colour()`.

**Comment by shadowtime2000** [comment]
We could copy and paste whenever we edit, or we could just have something like this at the bottom:
```javascript
TotallyRandom.prototype.colour = TotallyRandom.prototype.color
```

**Comment by superhackerboy** [comment]
I think having that at the bottom would be best

**Comment by Gridonyx** [comment]
Yeah, definitely the one-liner

**Comment by shadowtime2000** [comment]
Added it in #13

**Comment by superhackerboy** [comment]
Thank you!

**Comment by shadowtime2000** [comment]
I guess with this and the other changes the next version should be published on [npm](https://npmjs.org) or should we wait for the README redo to be completed.

**Comment by Gridonyx** [comment]
Best to wait for the readme update imo, I'll have it done tomorrow morning

**Comment by superhackerboy** [comment]
Yeah that's the only thing we're waiting on but no rush. It will be version 1.1 :) @shadowtime2000 where did you find this repo by the way? I appreciate your help with it all

**Comment by shadowtime2000** [comment]
@superhackerboy I was looking through [dev.to](https://dev.to) and I found your post about it

**Comment by superhackerboy** [comment]
Finally, something good came out of my blog posts hahaha
