### ISSUE TITLE
.from() to return unique

### ISSUE THREAD

**Issue by superhackerboy** [superhackerboy/totally-random#15]
The `.from()` method takes in an array and returns a random element from that array. You can also pass an optional parameter to return a new array of n elements. I think it would be a good idea to have a third optional parameter where the method will return a new array of unique elements. For instance, a deck of cards can't have more than 1 Ace of Spades.

`.from([arr], count, 'unique')`

Thanks to Andrew Richards for this idea!

**Comment by shadowtime2000** [comment]
I think I need a little bit of clarification. Is the `'unique'` parameter inside `.from()` meant to be a string? I think we could use a boolean instead.

**Comment by superhackerboy** [comment]
Yeah, that makes more sense. Good call!

**Comment by superhackerboy** [comment]
And it should, obviously, default to `false`

**Comment by downtownadambrown** [comment]
We need to rename .from() in this package to something else since .from() is a native javascript Array function.  I'm going to take a look at this method and offer a refactor in the next few days

**Comment by superhackerboy** [comment]
@downtownadambrown my second option was `.pick()`

**Comment by shadowtime2000** [comment]
Or we could do `.array()`.

**Comment by Gridonyx** [comment]
I can write the update to `.from()` to include the unique elements only option as well as update the docs. Is there a preferred name change for `.from()` that was decided upon?

**Comment by superhackerboy** [comment]
Let's just use `.array()` to keep it simple

**Comment by Gridonyx** [comment]
Alright sounds good

**Comment by Gridonyx** [comment]
I'll wait until after there is a decision on #22 before doing anything

**Comment by Gridonyx** [comment]
Alright so I'm more or less done with this enhancement, but there is an issue in where if `arr`'s length is less than the passed `count` while `unique` is `true`, it yields unpredictable results. 

i.e. 
```javascript
let arr = [1, 2, 3, 4, 5, 6, 7];
random.array(arr, 15, true);

//output: [4, 1, 5, 3, 7 ,6]```

I included a conditional warning:
```javascript
if (arr.length < count) console.warn("WARN: Array length shorter than count with unique=true, this will yield unpredictable output");
```

Is this sufficient handling or should I try to rethink this somehow?

**Comment by superhackerboy** [comment]
I think this should be fine but let's keep the errors standardized. @downtownadambrown used `throw "Whatever error message."` so let's do it that way.

**Comment by shadowtime2000** [comment]
I don't think we should use `throw "Error message"` in this case because I believe that could terminate the application. `console.warn` would be sufficient because we are only warning the user.

**Comment by Gridonyx** [comment]
Yeah I agree with @shadowtime2000 on this one, since it isn't an issue that breaks anything with the functionality of the code, a `console.warn` is sufficient just to let the developer know that output will be unpredictable

**Comment by superhackerboy** [comment]
Yeah I understand but the purpose of `unique` is to be sure each element is unique in the array being returned. Like the deck of cards example, shouldn't it error out if you're asked to draw 53 cards from a 52 card deck?

**Comment by Gridonyx** [comment]
Ah, fair enough. I guess it just depends on the use case, but you’re right, the output shouldn't be unpredictable

**Comment by superhackerboy** [comment]
Would this need refactoring? I could give it a stab tomorrow if you want

**Comment by Gridonyx** [comment]
Since it is using `throw` right now I don't think it would need any changes tbh
