### ISSUE TITLE
Error Statements

### ISSUE THREAD

**Issue by superhackerboy** [superhackerboy/totally-random#19]
I'm thinking we should handle errors in some way. For instance, if a user passed in 3 arguments to a method that accepts only 2. @Gridonyx suggested we use `console.error()` to print out the error message. Is that the best solution? What do other utility classes on NPM do?

**Comment by shadowtime2000** [comment]
As far as I know, we shouldn't be handling too many arguments. I feel like at the most we should only use `console.warn()` to tell them that they are using too many arguments.

**Comment by superhackerboy** [comment]
But what if they input the wrong data type?

**Comment by shadowtime2000** [comment]
If they input a wrong data type for an argument that does exist, then I think we should throw a `TypeError`.

**Comment by shadowtime2000** [comment]
I guess for this now would be a good time to start writing unit tests.

**Comment by superhackerboy** [comment]
Yeah this is a great idea since it's definitely become bigger than planned. I'm going to close this and make it a new issue. If no one wants to do it I'm interested in learning how testing works. Could use some guidance on what framework I should use
