### ISSUE TITLE
Playing with Chance

### ISSUE THREAD

**Issue by superhackerboy** [superhackerboy/totally-random#20]
What if we created a method where you pass in 2 arrays, the first for whatever the user wants randomly selected and the second for the chance each item would have to be picked. I'm not sure what to call it but for now let's call it chance.

Example:

```javascript
random.chance(["Earth", "Mercury", "Mars", "Saturn"], [18, 32, 21, 29])
```

So in the example, Earth would have an 18% chance of being picked, Mercury 32%, etc. Obviously they need to add up to 100 or we can give the last element in the array the remaining percentage if it's wrong.

**Comment by shadowtime2000** [comment]
I feel like that style of input would be found in python libraries. What about something like this:
```javascript
random.chance([
  {value: "Earth", chance: 18},
  {value: "Mercury", chance: 32},
  {value: "Mars", chance: 21},
  {value: "Saturn", chance: 29}
]);
```

**Comment by superhackerboy** [comment]
Would this be better?

```js
random.chance([
  {Earth , 18},
  {Mercury, 32}
]);
```

**Comment by shadowtime2000** [comment]
I don't believe it that would result in an array of valid Javascript objects. If we want to go through that path, we could do this:
```javascript
random.chance([
  ["Earth", 18],
  ["Mercury", 32]
]);
```

**Comment by superhackerboy** [comment]
Oops, sorry. I updated my comment

**Comment by shadowtime2000** [comment]
That would also work, but we would be limiting the user to only having strings as values because we would be returning only the keys.

**Comment by superhackerboy** [comment]
Very good point

**Comment by superhackerboy** [comment]
Ran into this

https://www.npmjs.com/package/chanced-element
