### ISSUE TITLE
Fix Contributing Section in README

### ISSUE THREAD

**Issue by superhackerboy** [superhackerboy/totally-random#24]
I added a .eslintrc.json file into the repo to adhere to [Airbnb's style guide](https://github.com/airbnb/javascript). I'm not sure how to reflect that info into the contributing section in the README.

**Comment by shadowtime2000** [comment]
We could create a `CONTRIBUTING.md` file and list it there. Though, I do not understand why `jsx`, `react`, and `react-hooks` eslint configs were added.

**Comment by superhackerboy** [comment]
I followed a [YouTube tutorial](https://www.youtube.com/watch?v=SydnKbGc7W8) and probably didn't catch that. You can remove them if you know how

**Comment by superhackerboy** [comment]
Does anything need to happen to this or can we close it?

**Comment by shadowtime2000** [comment]
I guess we could just create a `CONTRIBUTING.md` with some specifications and then close this.

**Comment by superhackerboy** [comment]
Do you mind doing that? I don't know if there's anything special we need to add since adding Travis, Gulp, etc. Would like to push 1.3 to NPM this week to show on my resume
Gridonyx <notifications@github.com> wrote:
“I guess we could just create a CONTRIBUTING.md with some specifications and then close this.”
