### ISSUE TITLE
Add Testing

### ISSUE THREAD

**Issue by superhackerboy** [superhackerboy/totally-random#25]
We should add unit testing to the repo. I've never done something like that before but I don't mind learning (something else I can put in my resume). But if anyone finds joy in doing it, be my guest! 

Also, should we be using a framework for it? If so, which?

**Comment by shadowtime2000** [comment]
I can work on the unit testing. I have used `mocha` before.

**Comment by superhackerboy** [comment]
Okay awesome. Would love to see how it works when you're done!

**Comment by shadowtime2000** [comment]
Because you can't test randomness with a testing library & framework, the only thing I can write tests for are error throws.

**Comment by superhackerboy** [comment]
Yeah that works. We need to have _something_
