### ISSUE TITLE
Should .to("numeric") return an integer instead of a string?

### ISSUE THREAD

**Issue by superhackerboy** [superhackerboy/totally-random#26]

**Comment by superhackerboy** [comment]
Thoughts on this?

**Comment by Gridonyx** [comment]
Could you elaborate? Because I see `.to()` returning a number
![image](https://user-images.githubusercontent.com/5842436/90254442-ba05b280-de10-11ea-8452-b715991b8ad2.png)

**Comment by Gridonyx** [comment]
Typo perhaps? Did you mean `.string("numeric")`?

**Comment by superhackerboy** [comment]
Whoops lmao yeah that one

**Comment by Gridonyx** [comment]
Lol no worries, so for this I am inclined to say no, since the function is `.string()` the user *should* expect a string to be returned. If they, for whatever reason, wanted that to be a number they could just `parseInt()` it

**Comment by superhackerboy** [comment]
Solid reasoning!
