### ISSUE TITLE
.color() rgb, rgba, hsl, hsla whitespace

### ISSUE THREAD

**Issue by superhackerboy** [superhackerboy/totally-random#27]
Also whoever works on this could you please add a `count` parameter!

![Screen Shot 2020-08-11 at 4 19 19 PM](https://user-images.githubusercontent.com/59143065/89946112-6fa5eb00-dbf0-11ea-8875-c242c69ee470.png)

**Comment by Gridonyx** [comment]
Subsequently I can also fix this one while doing #28 and #29, quick fix

**Comment by superhackerboy** [comment]
Not sure if you partially fixed the color refactor or if my console is doing this but here's an output I'm getting:
```
rgba(235,                 245,                 82,                 0.23)
```

**Comment by Gridonyx** [comment]
It must be interpreting the whitespace used for code legibility, despite me adding the `\` breaks at the end. I'll take another quick look at it and do a new PR

**Comment by Gridonyx** [comment]
Alright working on a new refactor right now
