### ISSUE TITLE
.float()

### ISSUE THREAD

**Issue by superhackerboy** [superhackerboy/totally-random#35]
I was thinking about this last night. Is there ever a need to get a random float number? What if we created a method that did something like this:

```js
random.floatTo(99, [placeValue = 10])
```

This would serve almost the same purpose as our already existing `.to()` except you can pass an optional second parameter. In the example above it will return a number between 1 to 99 in the tenths place value. So it could return 1.5, 16.9, 88.8, etc. 

Maybe the maximum acceptable `placeValue` could be `1000000000` which is 1 hundred billionths (?).

Thoughts?

**Comment by shadowtime2000** [comment]
It seems like it could have some use. I do not believe we would have to play a maximum accepted `placeValue`.

**Comment by superhackerboy** [comment]
So just let the user handle how they want to take care of the float?

**Comment by shadowtime2000** [comment]
Yes. If going too precise causes performance issues then that's up to them to solve.

**Comment by superhackerboy** [comment]
This is a lot harder than I thought it would be. I found this solution online. How can I possible check to see if `max` will ever hit 2?

```js
function getRandomIntInclusive(min, max) {
	min = Math.ceil(min);
	max = Math.floor(max) - 1;
	return Math.random() * (max - min + 1) + min;
}

let num = 0;
let count = 0;

do {
	num = getRandomIntInclusive(1, 2);
	count++;
} while (num !== 2);
```

**Comment by Gridonyx** [comment]
Unless I'm misunderstanding, could we not just do something like:

```js
return this.to(99) + this.randomizer();
```

**Comment by superhackerboy** [comment]
Damn, definitely overthought that one. I like your first solution, however, this is what I want it to look like:

```js
floatTo(num, count = 1) {
    const arr = [];

    for (let i = 0; i < count; i++) {
      arr.push(this.to(num) + this.randomizer());
    }

    return count === 1 ? arr[0] : arr;
  }
```

I want `.floatTo()` to function in the same way `.to()` does where it will return a number starting from 1 to `num`. As it stands, it will return a number from 1 to `num + 1` (excluding num + 1). So, for example, `.floatTo(2)` can return 2.123456 but shouldn't it stop at 2? We can easily do `arr.push(this.to(num) + this.randomizer() + 1);` but then it will be from 0 to `num`. Am I over thinking this again?

**Comment by shadowtime2000** [comment]
What about this:
```javascript
floatTo(placeValue, count=1) {
    if (placeValue%10 != 0) throw new Error("placeValue must be divisible by 10!");
    if (count < 1) throw countError;
    const oneToNine = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];
    const arr = [];
    for (let i = 0; i < count; i++) {
        var e = 0;
        for (let j = 0; j < placeValue; j=j*10) {
            e = e + (this.array(oneToNine)/j)
        }
        arr.push(e);
    }
    return count === 1 ? arr[0] : arr;
}
```

**Comment by superhackerboy** [comment]
Okay, I think I found a solution but would `.floatTo(3)` include the integer 3? I also removed the second `throw new Error()` statement in `.to()`. No idea why that was there but it prevented us from passing in a negative number

```js
floatTo(num, count = 1) {
    if (count < 1) throw countError;
    const arr = [];

    for (let i = 0; i < count; i++) {
      arr.push(this.to(num - 1) + this.randomizer());
    }

    return count === 1 ? arr[0] : arr;
  }
```

**Comment by shadowtime2000** [comment]
I don't think `.floatTo()` should operate like `.to()`. Shouldn't it just return a decimal number up to a certain place value? Why do we need to think about having it go up to certain numbers? It could just be 0.423748917283904.

**Comment by shadowtime2000** [comment]
And for that I believe this would work but I haven't tested it:
```javascript
floatTo(placeValue, count=1) {
    if (placeValue%10 != 0) throw new Error("placeValue must be divisible by 10!");
    if (count < 1) throw countError;
    const oneToNine = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];
    const arr = [];
    for (let i = 0; i < count; i++) {
        var e = 0;
        for (let j = 0; j < placeValue; j=j*10) {
            e = e + (this.array(oneToNine)/j)
        }
        arr.push(e);
    }
    return count === 1 ? arr[0] : arr;
}
```

**Comment by Gridonyx** [comment]
I mean if it just returns a float between 0 and 1 then people can just use Math.random() for that

**Comment by shadowtime2000** [comment]
But this allows you to decide place values

**Comment by superhackerboy** [comment]
I think what I'm wanting it to do is function just like `.to()` but with a float. So if you do `.floatTo(10)` it will return a float between 1 and 10 inclusive. So 10.235623 is invalid.

@shadowtime2000 I agreed with your first statement. Let the user figure out what they want to do with the return number instead of dealing with it in the method.

**Comment by shadowtime2000** [comment]
In that case the method I gave can be modified a little to do that.

**Comment by superhackerboy** [comment]
It looks a bit complicated. Does it do the same function mine does?

**Comment by Gridonyx** [comment]
I think including place value just wouldn't be good, I think it would be best to just throw a number back at the user, and as mentioned before, let them handle if they want to round it themselves. That makes things incredibly straightforward then:

```js
floatTo(num, count = 1) {
  if (count < 1) throw countError;

  const arr = [...Array(count)]
    .map(() => this.to(num) + this.randomizer());

  return count === 1 ? arr[0] : arr;
}
```

**Comment by superhackerboy** [comment]
@Gridonyx I like your code but I don't like how it goes past `num` like I've been mentioning for a while now. if `.to(3)` returns 1-3 inclusive on both ends, it doesn't make sense that `.floatTo(3)` can return 3.12345. 3 should be the last number that can be returned, right?

Can someone check my solution?
```js
floatTo(num, count = 1) {
    if (count < 1) throw countError;
    const arr = [];

    for (let i = 0; i < count; i++) {
      arr.push(this.to(num - 1) + this.randomizer());
    }

    return count === 1 ? arr[0] : arr;
  }
```

**Comment by Gridonyx** [comment]
@superhackerboy so it would just be my exact code but you'd make it `num-1` like in yours (idk if you could tell but I have an aversion to for loops lmao).

**Comment by Gridonyx** [comment]
fwiw the map is faster:
![image](https://user-images.githubusercontent.com/5842436/90180279-b9234100-dd7c-11ea-9e11-c28a63363c51.png)

**Comment by superhackerboy** [comment]
So should we change all for loops to that? What about for...in?

**Comment by shadowtime2000** [comment]
I believe for...in would be the same thing. It is just another for loop with less code.

**Comment by superhackerboy** [comment]
Ah I didn't know that it was just syntactical sugar

**Comment by shadowtime2000** [comment]
@superhackerboy Are you going to close this issue now that it was added in [97a0](https://github.com/superhackerboy/totally-random/commit/97a0f84d5b2274fd6d07cc4884ec0f172760e84d)? The benchmark discussion could be moved to another issue.
