### ISSUE TITLE
Gulp Task Runner

### ISSUE THREAD

**Issue by shadowtime2000** [superhackerboy/totally-random#38]
It looks like this project is slowly becoming more advanced and complicated. We are using ESLint for code consistency and we have already wrote unit tests. I am wondering if everybody would be fine with using `Gulp` with `Babel`, `UglifyJS`, `ESLint`, and `mocha` for building. Then, we would have to move the source code to `src` and use `dist` as an output folder for `Gulp`.

**Comment by shadowtime2000** [comment]
This would of course require @superhackerboy or anyone else with specific permissions to link a continuous integration service to run gulp tasks on pull requests.

**Comment by superhackerboy** [comment]
@Gridonyx thoughts?

**Comment by shadowtime2000** [comment]
I would also just like to point out that I can write the `gulpfile.js` so I am not trying to put work on anyone else.

**Comment by shadowtime2000** [comment]
Because committing built files is kind of unnecessary if we follow this route we could add `dist` to the `.gitignore` and have `Gulp` run as a `prepublish` script for when @superhackerboy publishes it to `npm`.

**Comment by shadowtime2000** [comment]
@superhackerboy What are your opinions on this change?

**Comment by superhackerboy** [comment]
This is beyond my expertise. Wondering @Gridonyx thoughts

**Comment by Gridonyx** [comment]
Yeah, I'm down for this change. Would we want to add browserify into the mix as well?

**Comment by shadowtime2000** [comment]
I guess so. I really don't know what has happened to `browser.js`. In #22 it was said in a commit description that it is now exported in `Webpack` versions which is a little bit confusing because I have never worked with `Webpack` before. With `browserify` I guess we could just kind of `browserify` the `totallyRandom.js` into `browser.js`.

**Comment by shadowtime2000** [comment]
Can anyone else make heads or tails of what happened to `browser.js`? I think we need to add `Webpack` to transform that `import` and `export` or something like that. I guess moving to use `browserify` for that would be better.

**Comment by Gridonyx** [comment]
@downtownadambrown could you chime in?

**Comment by shadowtime2000** [comment]
Instead of having to go into the complexities of `browserify` and `Webpack` if we did you use `Gulp` we could use [gulp-umd](https://github.com/eduardolundgren/gulp-umd) and delete `index.js` and `browser.js`. Then, we could rename `totallyRandom.js` to `index.js` and just point to that in the `package.json`.

**Comment by Gridonyx** [comment]
@shadowtime2000 Sounds good to me 👍🏼

**Comment by superhackerboy** [comment]
Is bringing this to browser because we think people will use it or because we can?

**Comment by Gridonyx** [comment]
I'd say a bit of both

**Comment by shadowtime2000** [comment]
@superhackerboy Here is my explanation of what changes were made in #44:

1. I changed the unit tests for `to` because you removed the negative number error for `to` in a commit

2. I added the `Gulp` task runner. It is a tool which allows you to create plugins which can be used as building blocks for a streamlined build process. Here are the plugins I used in the order they were used:

- ESLint

- Babel which will transform `ES6+` to `ES5` so it can be used by the plugin below

- UglifyJS is a JavaScript tool to minify code

- UMD is a set of design patterns to allow the same code to run in both browser and Node. It just checks if certain values like `window` and `module` exist to see how it should export the code.

**Comment by superhackerboy** [comment]
Okay cool. Yeah I removed the error line in #1 because `.to()` should be allowed to take in a negative number. We have it written that way in the docs. 

What do you need from me to get Gulp up and running?

**Comment by shadowtime2000** [comment]
@superhackerboy I need you to link [Travis CI](https://travis-ci.org/) to this repo. Once that is done, create a file named `.travis.yml` with the following text:
```yml
before_script:
  - npm install -g gulp-cli
script: gulp
```
But before you do that, you should probably merge #46 or else every time it does a build it will give the error `gulpfile.js not found` or something like that. You will have to clear up the conflicts.

**Comment by shadowtime2000** [comment]
When clearing up the conflicts you will most likely only need to copy the `dist/totallyRandom.js` into `src/index.js`, and then have my code for `dist/totallyRandom.js` exist and it should work.

**Comment by shadowtime2000** [comment]
Or you could also allow the code inside this repo to exist and it should work fine

**Comment by shadowtime2000** [comment]
I removed the conflicts now.

**Comment by downtownadambrown** [comment]
hey sorry i didnt see this until today, been busy.

Gulp works, i was going to go the webpack route once i got more time, but im glad we have something

**Comment by downtownadambrown** [comment]
@shadowtime2000 i like where you are going with it

**Comment by shadowtime2000** [comment]
I copied over the new changes for `dist/totallyRandom.js` into `src/index.js` please now put your work inside `src/index.js` for changes.

**Comment by shadowtime2000** [comment]
Once #46 is merged of course.

**Comment by shadowtime2000** [comment]
@superhackerboy Can you please [link a CI now?](https://github.com/superhackerboy/totally-random/issues/38#issuecomment-674442668)

**Comment by superhackerboy** [comment]
I can tomorrow enjoying my sunday :D

**Comment by superhackerboy** [comment]
@shadowtime2000 done. Let me know if that was done right

**Comment by shadowtime2000** [comment]
@superhackerboy I believe Travis CI has been successfully linked.
