### ISSUE TITLE
Loops v. Array Functions

### ISSUE THREAD

**Issue by Gridonyx** [superhackerboy/totally-random#40]
Can close #35, continue the conversation on for loop types (`for`, `for...in`, `for...of`) vs array function (`.map`) performance.

To start, `for`, `for...in`, and `for...of` do fundamentally function and perform differently from one another. 

A standard `for` loop is running over a newly initialized iterator and performing a given statement(s)

`for...in` returns enumerable property names, and doesn't necessarily return indexes in any order, so isn't generally something that is recommended to use on arrays.
```js
const arr = ['a', 'b', 'c', 'd'];
for (const i in arr) {
  console.log(i);
}
// Output: 
// 0,
// 1,
// 2,
// 3
```

`for...of` uses object-specific iterators (i.e. array indexes) and subsequently returns values in proper order.
```js
const arr = ['a', 'b', 'c', 'd'];
for (const i of arr) {
  console.log(i);
}
// Output: 
// a,
// b,
// c,
// d
```

**Comment by Gridonyx** [comment]
**`for`**
```js
floatTo(num, count = 1) = {
  if (count < 1) throw countError;
  const arr = [];

  for (let i = 0; i < count; i++) {
    arr.push(this.to(num - 1) + this.randomizer());
  }

  return count === 1 ? arr[0] : arr;
}
```
**`.map`**
```js
floatTo(num, count = 1) = {
  if (count < 1) throw countError;

  const arr = [...Array(count)]
    .map(() => this.to(num - 1) + this.randomizer());

  return count === 1 ? arr[0] : arr;
}
```

**`for...of`**
```js
floatTo(num, count = 1) = {
  if (count < 1) throw countError;
  const arr = new Array(count);

  for (const [i, v] of arr.entries()) {
    if (!v) arr[i] = (this.to(num - 1) + this.randomizer());
  }

  return count === 1 ? arr[0] : arr;
}```

![image](https://user-images.githubusercontent.com/5842436/90250266-d4885d80-de09-11ea-927f-24a808ffe0cc.png)

**Comment by superhackerboy** [comment]
Should I create an issue to make all loops `.map` where possible?

**Comment by Gridonyx** [comment]
Yeah if you're alright with that change let's go for it
