### ISSUE TITLE
Bug: Array function

### ISSUE THREAD

**Issue by Gridonyx** [superhackerboy/totally-random#43]
When `unique = true` in the `array` function, it can return an array whose length is less than `count` thus yielding inaccurate output than what is passed in parameters

**Comment by shadowtime2000** [comment]
Doesn't it throw an error in that scenario?

**Comment by Gridonyx** [comment]
Nah, because of how making the unique array is done, there are no errors handling it. Because the array `newArr` is getting created with length `count` and populated with values. Then it checks if `unique = true` and subsequently makes the unique array with `[...new Set(newArr)]`  which is where the bug comes in.

**Comment by Gridonyx** [comment]
I have written code that fixes the issue, but it uses a `while` loop which I am apprehensive about

```js
array(arr, count = 1, unique = false) {
  if (arr.length < count && unique) throw new Error(
    "Array length must be larger than count if unique = true"
  );

  let newArr = [...Array(count)].map(
    () => arr[this.to(arr.length - 1)]
  );
  
  if (unique) {
    newArr = [...new Set(newArr)];

    while (newArr.length < count) {
      const addElem = arr[this.to(arr.length - 1)];

      if (newArr.includes(addElem)) continue;
      else newArr.push(addElem);
    }
  }

  return count === 1 ? newArr[0] : newArr;
}
```

**Comment by superhackerboy** [comment]
Just pretend I wrote it then ;)

**Comment by Gridonyx** [comment]
I mean I guess we can just push that until I find a more elegant solution since it does fix the issue without affecting performance much. I'm just worried about if a huge array and count get passed
