### ISSUE TITLE
Double check how to install instructions

### ISSUE THREAD

**Issue by superhackerboy** [superhackerboy/totally-random#53]
@shadowtime2000 again I apologize since I'm still new to this. I updated the npm to our current GH version. The package doesn't work and if it does, we need to be clearer on how the user installs it in the README.

When I tried using it browser:

```
Uncaught ReferenceError: require is not defined
    at app.js:1
```

When I tried to use it in Node:

```
internal/modules/cjs/loader.js:337
      throw err;
      ^

Error: Cannot find module '/Users/markharless/Desktop/untitled folder/node_modules/totally-random/dist/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:329:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:690:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1017:27)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/Users/markharless/Desktop/untitled folder/app.js:1:23)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/markharless/Desktop/untitled folder/node_modules/totally-random/package.json',
  requestPath: 'totally-random'
}
```

If you can verify if I'm a dumbass let me know. Otherwise, I'll figure out how to revert the npm package to its previous working state.

**Comment by Gridonyx** [comment]
I know you have put a fair bit of work into the implementation of gulp, but I think it may be adding an unnecessary amount of friction in terms of working on this project. While I understand the purpose of it, I feel as though it may be overkill based on the project's size and scope. Would we be in agreeance on paring things back a bit?

**Comment by shadowtime2000** [comment]
Yes. But how would we allow people to use `totally-random` in the browser?

**Comment by Gridonyx** [comment]
I think we need to evaluate what ES6 syntax code we're using, and what browsers support it natively. As far as I'm aware, it is really only IE11 that has issues with ES6 syntax as illustrated by the [ES6 Compatibility Table](https://kangax.github.io/compat-table/es6/)

**Comment by superhackerboy** [comment]
I think it would be best if we completely finished the class method to as good as we can get it first. Get it working for Node then we can do browser compatibility.
